In [5]:
import pandas as pd

In [29]:
import mysql.connector
import time

In [30]:
conn = mysql.connector.connect(host='localhost',user='root',password='Root@786123#',database='world')

In [31]:
pd.read_sql_query('SELECT * FROM city', conn)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18164\929584838.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * FROM city', conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [32]:
cursor = conn.cursor()

In [33]:
data = cursor.execute('select * from city')

In [34]:
cursor

In [35]:
data = pd.read_json('https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json')

In [36]:
data

,name,language,id,bio,version
0,Adeel Solangi,Sindhi,V59OF92YF627HFY0,Donec lobortis eleifend condimentum. Cras dict...,6.10
1,Afzal Ghaffar,Sindhi,ENTOCR13RSCLZ6KU,"Aliquam sollicitudin ante ligula, eget malesua...",1.88
2,Aamir Solangi,Sindhi,IAKPO3R4761JDRVG,Vestibulum pharetra libero et velit gravida eu...,7.27
3,Abla Dilmurat,Uyghur,5ZVOEPMJUI4MB4EN,Donec lobortis eleifend condimentum. Morbi ac ...,2.53
4,Adil Eli,Uyghur,6VTI8X6LL0MMPJCC,"Vivamus id faucibus velit, id posuere leo. Mor...",6.49
...,...,...,...,...,...
192,Kristín Sigurðardóttir,Icelandic,ZP5TBBYX6RI2UJ31,Cras dictum dolor lacinia lectus vehicula rutr...,2.80
193,Rohini Vasav,Hindi,UEFML43TCGS04KWM,"Ut accumsan, est vel fringilla varius, purus a...",9.30
194,Sunil Kapoor,Hindi,VY2A0APGVHK5NAW2,"Proin tempus eu risus nec mattis. Ut dictum, l...",8.04
195,Zamokuhle Zulu,isiZulu,XU7BX2F8M5PVZ1EF,Etiam congue dignissim volutpat. Phasellus tin...,8.39
196,Bhupesh Menon,Hindi,0CEPNRDV98KT3ORP,Maecenas tempus neque ut porttitor malesuada. ...,2.69

In [37]:
import requests
import http.client
import json

In [38]:
host_name = "anime-db.p.rapidapi.com"
api_key = "ec6be5b175msh08ed18768cb5499p16eb79jsna2ca958953eb"
conn = http.client.HTTPSConnection(host_name)

In [39]:
headers = {
    'x-rapidapi-key': api_key,
    'x-rapidapi-host': host_name
}

In [42]:
# get all pages data
df = pd.DataFrame()
for page in range(1,60):
    url = f"/anime?page={page}&size=100&sortBy=ranking&sortOrder=asc"
    conn.request("GET", url, headers=headers)
    res = conn.getresponse()
    data = res.read()
    data = json.loads(data)
    try:
        page_df = pd.DataFrame(data['data'])[['_id', 'title', 'ranking', 'genres', 'episodes']]
        df = pd.concat([df, page_df], ignore_index=True)
        time.sleep(1)
    except Exception as e:
        print(e)
df.shape

(5900, 5)

In [43]:
df.to_csv("anime_list.csv")