In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('advertising_sales_linear_regression.csv')

In [5]:
df.head(10)

   TV_Ads_Spend  Radio_Ads_Spend  SocialMedia_Ads_Spend  Sales_in_Millions
0           202               76                     78              14.74
1           155               79                      6              10.08
2           139                6                     62               8.48
3           133               25                     18               6.58
4           217               27                     57              12.14
5            14               91                     26               4.85
6           237               91                     36              12.20
7           241               43                      4              10.96
8           284               50                     41              14.12
9           173               52                     26               8.11

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   TV_Ads_Spend           120 non-null    int64
 1   Radio_Ads_Spend        120 non-null    int64
 2   SocialMedia_Ads_Spend  120 non-null    int64
 3   Sales_in_Millions      120 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 3.9 KB

In [7]:
df.describe()

       TV_Ads_Spend  Radio_Ads_Spend  SocialMedia_Ads_Spend  Sales_in_Millions
count    120.000000       120.000000              120.00000         120.000000
mean     166.016667        49.883333               40.95000          10.044750
std       85.848409        27.877337               21.48435           3.910694
min       14.000000         5.000000                2.00000           2.240000
25%       93.000000        26.000000               23.00000           7.177500
50%      173.500000        50.000000               40.50000          10.010000
75%      239.500000        73.250000               59.00000          13.195000
max      299.000000        99.000000               79.00000          19.190000

In [18]:
X = df[['TV_Ads_Spend', 'Radio_Ads_Spend', 'SocialMedia_Ads_Spend']]
Y = df[['Sales_in_Millions']]

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, random_state=42)

In [19]:
scaler = StandardScaler()
scaler.fit(X_train) # Fit on training data

# Transform
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [20]:
model = LinearRegression()
model.fit(X_train_scaled, Y_train)

Y_pred = model.predict(X_test_scaled)
print("Test Prediction", Y_pred)

mae = mean_absolute_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("R2 Score:", r2)

Test Prediction [[13.28366749]
 [ 3.44760307]
 [11.99522489]
 [ 8.73630831]
 [11.25983056]
 [12.1200532 ]
 [12.63992901]
 [12.63405138]
 [ 6.55766611]
 [11.75662716]
 [11.76187274]
 [ 6.05243067]
 [ 4.70489809]
 [12.29974618]
 [ 4.97652389]
 [16.23035742]
 [ 5.83863857]
 [13.97983419]
 [11.9843943 ]
 [ 8.5289596 ]
 [ 8.53250594]
 [11.17344574]
 [ 7.76183443]
 [ 8.32327088]]
MAE: 1.1977043119597708
MSE: 2.187367623154712
R2 Score: 0.8114148925665738

In [25]:
"""
Which ad platform contributes the most to sales?
If the company increases Social Media spend by 10 units, how much will sales increase?
Should the company reduce spending on any platform? Justify
"""

coeh = pd.DataFrame(model.coef_, columns=X.columns)

In [26]:
coeh

   TV_Ads_Spend  Radio_Ads_Spend  SocialMedia_Ads_Spend
0      3.442853         0.974567               0.869358

In [34]:
# 1. --> TV Ads platform contributes the most sales
print(f"If the company increases Social Media spend by 10 units, it will incresed by {0.869358 * 10 } million units" )

If the company increases Social Media spend by 10 units, it will incresed by 8.693579999999999 million units

In [44]:
#  let's take profit margin is 30% 
# ROI=Revenue−Cost/Cost
	
ROI_TV = (3.442853 - 1 )/1
ROI_RD = (0.974567 - 1)/1
ROI_SC = (0.869358 - 1 )/1
print(f"TV: {ROI_TV} \n Radio : {ROI_RD} \n SocialMedia : {ROI_SC}")

TV: 2.442853
 Radio : -0.02543300000000004
 SocialMedia : -0.13064200000000004

In [41]:
# basis of above results so 
# TV -->very Strong
# Radio --> NO
# SocialMedia --> No